version: '3'


services:
  backend-medical-documentation-service:
    build: ./backend
    ports:
      - 6969:8000
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:16-bullseye
    env_file:
      - .env
    ports:
      - 5433:5432

  frontend-medical-documentation-service:
    build: ./frontend
    ports:
      - 2137:3000
    depends_on:
      - backend-medical-documentation-service
