version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: fastapi_backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./app/doctor_opinions.db
      - FRONTEND_URL=http://frontend:4200
    hostname: backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  frontend:
    build:
      context: ./frontend
    container_name: angular_frontend
    environment:
      - BACKEND_URL=http://backend:8000
    ports:
      - "4200:4200"
    hostname: frontend
