services:
  app:
    build: .
    env_file: .env
    ports:
      - "8095:${SERVER_PORT}"
    depends_on:
      db:
        condition: service_healthy
    command: [ "sh", "-c", "/backend/bin/migrate up && /backend/bin/api" ]
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:${SERVER_PORT}/livez" ]
      interval: 5s
      timeout: 5s
      retries: 5
    # volumes:
    #    - ./postgres-data:/var/lib/postgresql/data
    restart: always

  db:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 3s
      timeout: 5s
      retries: 5
    restart: always
