# Generated by Django 5.0.4 on 2024-06-05 20:00

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AvailabilityInterval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start", models.TimeField()),
                ("end", models.TimeField()),
            ],
            bases=(models.Model, api.models.CustomUpdate),
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=255)),
                ("doctor_id", models.CharField(max_length=255)),
                ("price", models.IntegerField(default=100)),
            ],
            bases=(models.Model, api.models.CustomUpdate),
        ),
        migrations.CreateModel(
            name="AvailabilityTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "friday",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="friday",
                        to="api.availabilityinterval",
                    ),
                ),
                (
                    "monday",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="monday",
                        to="api.availabilityinterval",
                    ),
                ),
                (
                    "saturday",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="saturday",
                        to="api.availabilityinterval",
                    ),
                ),
                (
                    "sunday",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sunday",
                        to="api.availabilityinterval",
                    ),
                ),
                (
                    "thursday",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="thursday",
                        to="api.availabilityinterval",
                    ),
                ),
                (
                    "tuesday",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tuesday",
                        to="api.availabilityinterval",
                    ),
                ),
                (
                    "wednesday",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="wednesday",
                        to="api.availabilityinterval",
                    ),
                ),
            ],
            bases=(models.Model, api.models.CustomUpdate),
        ),
        migrations.CreateModel(
            name="DoctorToAvailabilityTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("doctor_id", models.CharField(max_length=255)),
                (
                    "availability_table",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.availabilitytable",
                    ),
                ),
            ],
            bases=(models.Model, api.models.CustomUpdate),
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField()),
                ("customer_id", models.CharField(max_length=255)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.service"
                    ),
                ),
            ],
            bases=(models.Model, api.models.CustomUpdate),
        ),
    ]
